### PR TITLE
Updated eslint packages

### PR DESCRIPTION
**Pull request by reconstructions**
### Updating package for `eslint-config-shakacode`:

I updated the `eslint-config-shakacode` package from version `^14.1.1` to `16.0.0-rc.3`. This flagged some minor issues and places where destructuring could be used.  These were the same errors seen with the `^15.0.0` version:

#### `<Link>` anchors invalid:

The `<Link>` elements in [`client/app/bundles/comments/layout/Layout.jsx`](https://github.com/shakacode/react-webpack-rails-tutorial/blob/380c89ad2cea2fcc27c548125849ecc14d48ee04/client/app/bundles/comments/layout/Layout.jsx#L20) produced ESLint errors with the new config:

```
The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid
```

Rules to fix this are [documented](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#rule-details), but the examples are in JSON and I couldn't convert or figure out a YAML version which would work in `eslintrc.yml`  

I tried all of the following with no success, including vanilla JSON > YAML conversions:

```
jsx-a11y/anchor-is-valid:
  - error
  - components:
    - Link
    specialLink:
    - hrefLeft
    - hrefRight
    aspects:
    - noHref
    - invalidHref
    - preferButton
```
And:
```
jsx-a11y/anchor-is-valid: [error, {components: [Link], specialLink: [hrefLeft, hrefRight], aspects: [noHref, invalidHref, preferButton]}]
```
I finally turned it off: `jsx-a11y/anchor-is-valid: off`.  Maybe someone better at YAML can fix this.

#### Changed an `<a>` link to a `<button>` with styling:

A link is used instead of a button in [`CommentBox.jsx`](https://github.com/shakacode/react-webpack-rails-tutorial/blob/380c89ad2cea2fcc27c548125849ecc14d48ee04/client/app/bundles/comments/components/CommentBox/CommentBox.jsx#L95), which gives the ESLint warning:

```
Anchor used as a button. Anchors are primarily expected to navigate. Use the button element instead  jsx-a11y/anchor-is-valid
```

I [replaced the link with a button](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md) and styled it to look like the other links.

#### Newlines after parenthesis:

There were 18 places where newlines after parenthesis were causing ESLint errors, for example in [commentsStore.js:17](https://github.com/shakacode/react-webpack-rails-tutorial/blob/380c89ad2cea2fcc27c548125849ecc14d48ee04/client/app/bundles/comments/store/commentsStore.js#L17).  

It was tough to figure out what the expected behavior should / would be from the [docs](https://eslint.org/docs/rules/function-paren-newline).  These errors were thrown with the `eslintrc.yml` default value of `"function-paren-newline": ["error", "multiline"]`, but changing "multiline" to "consistent" took care of it.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/426)

### CODE REVIEW

**Comment by justin808** [comment]
@reconstructions Looks great so far. @alexfedoseev will take a peek.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/package.json, line 108 at r1](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-L-AfNAtp2WlQuNw3puT:-L-AfNAtp2WlQuNw3puU:b-gejznv) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/69a1840d118538b9c5577910cf0640b3b1d66b2f/client/package.json#L108)):*
> ```JSON
>     "chai-immutable": "^1.6.0",
>     "eslint": "^4.11.0",
>     "eslint-config-shakacode": "^16.0.0-rc.3",
> ```

we can maybe 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-:-L-Ag2OHGG1xr4gD36fz:bxgjltw)*

**Comment by reconstructions** [comment]
Thanks @justin808. Travis finished building but froze in test failures (tests were green locally), and probably should be restarted.  Let me know if it would be easier for me to pull again instead.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-:-L-AkCOP3sRpzVgNkzpX:b255ntn)*

**Comment by alexfedoseev** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[client/.eslintrc.yml, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-L-CA8CD7dPd2CIWzHMK:-L-CA8CD7dPd2CIWzHML:bjz9f8b) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/69a1840d118538b9c5577910cf0640b3b1d66b2f/client/.eslintrc.yml#L20)):*
> ```YAML
> rules:
>   import/extensions: [2, { js: "never", jsx: "never" }]
>   function-paren-newline: ["error", "consistent"]
> ```

Just FYI, we don't see this issue on fng.

---

*[client/package.json, line 108 at r1](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-L-AfNAtp2WlQuNw3puT:-L-C8QF85Agdx2bQACfP:b-vrfjio) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/69a1840d118538b9c5577910cf0640b3b1d66b2f/client/package.json#L108)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

we can maybe 
</blockquote></details>

FYI Published `16.0.0` (no changes from RC).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-:-L-CAY9VMrM8hlenOrOa:bnfp4nl)*

**Comment by reconstructions** [comment]
*[client/.eslintrc.yml, line 20 at r1](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-L-CA8CD7dPd2CIWzHMK:-L-DsDC02iOVnGwJsE-X:b8yfnj0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/69a1840d118538b9c5577910cf0640b3b1d66b2f/client/.eslintrc.yml#L20)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary><blockquote>

Just FYI, we don't see this issue on fng.
</blockquote></details>

I bumped the packaged to 16.0.0, and was able to --fix the newline errors (having cleaned up the unfixable ones before).  ESLint fixed them by putting everything on one (long) line.  Are their line breaks in FNG?  Or maybe they got --fixed and are long?  I will update this PR with the 16.0.0 package to see if that fixes the build.  Let me know if you would prefer the `function-paren-newline` `consistent` config or --fixed long lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426)*

**Comment by reconstructions** [comment]
*[client/package.json, line 108 at r1](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426#-L-AfNAtp2WlQuNw3puT:-L-YbN6CKZTjQyatjbfm:b-f5eg60) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/69a1840d118538b9c5577910cf0640b3b1d66b2f/client/package.json#L108)):*
<details><summary><i>Previously, alexfedoseev (Alex Fedoseev) wrote…</i></summary><blockquote>

FYI Published `16.0.0` (no changes from RC).
</blockquote></details>

I bumped the version to 16.0.0, thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/426)*

**Comment by justin808** [comment]
Thanks @reconstructions!

**Pull request merged**
