### PR TITLE
Vagrant setup

### PR DESCRIPTION
**Pull request by mapreal19**
- Solution adapted from https://railsbox.io/boxes/e99e45ecc562

Commands for setup:
```
cd railsbox/development
vagrant up

vagrant ssh
cd ../../react-webpack-rails-tutorial/
bundle install
rake db:setup
npm install

foreman start -f Procfile.dev
```

Issues:

- [ ]  Feature specs need drivers

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/241)

### CODE REVIEW

**Comment by mapreal19** [comment]
Review status: 0 of 115 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/server-rails-hot.js, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/241#-KC1xgPi_sZqj-BKXxqz:-KC1xgPi_sZqj-BKXxr-:278896676) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/05e416985393b4d1272c5db22299087b02b5e6e9/client/server-rails-hot.js#L21)):*
Need this for having hot reload working

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/241)*

**Comment by justin808** [comment]
@mapreal19 This looks potentially very useful. @dylangrafmyre, @jbhatab, What do you two think of this?

**Comment by mapreal19** [comment]
Indeed. 

This could become even simpler with a custom script that would do all the setup during provision (i.e.: `bundle install, rake db:setup, npm install, ...`)

And we could have our own [custom commands](https://www.vagrantup.com/docs/plugins/commands.html), something alone the lines `vagrant run --dev`

A newcomer or a designer would love just to do this for the setup:
```
vagrant up
vagrant run --dev
```

More info:
- Good answer by the creator of Vagrant: http://stackoverflow.com/a/21314566/2273578
- https://www.vagrantup.com/docs/why-vagrant/

**Comment by dylangrafmyre** [comment]
@justin808 @mapreal19 I think you would be way better off using Docker and Docker-Compose for this solution. But a Vagrantfile could be in place for those to who like to `vagrant up`.  

---

Review status: 0 of 115 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/241#-:-KC6h070t30465Wyzplp:-1625744872)*

**Comment by mapreal19** [comment]
@dylangrafmyre Vagrant supports Docker too if you want: https://www.hashicorp.com/blog/feature-preview-vagrant-1-6-docker-dev-environments.html

Quoting Mitchell (creator of Vagrant): 

> Vagrant is not for managing machines, Vagrant is for managing development environments. The fact Vagrant spins up machines is mostly historic. The next version of Vagrant has first class support to spin up dev environment using Docker as a provider directly on the host or any VM (Mac, Win). It can also spin up raw LXC if thats what someone wants (again, on the host or VM). Vagrant is interested in doing what is best to create a portable development environment, whether that means creating a VM or not

> Vagrant 1.6 has first-class support for docker-based development environments. This will not launch a virtual machine on Linux, and will automatically launch a virtual machine on Mac and Windows. The end result is that working with Docker is uniform across all platforms, while Vagrant still handles the tedious details of things such as networking, synced folders, etc.

**Comment by justin808** [comment]
@mapreal19 How about we close this PR and put a reference in the readme or /docs file that references this?

**Comment by mapreal19** [comment]
@justin808 good idea. This is low priority, we could work on it in the future

**Comment by justin808** [comment]
Let's close this PR, as I want to minimize the open ones.

**Pull request closed without merging**
