### PR TITLE
fix localhost location

### PR DESCRIPTION
**Pull request by tjnet**
fix localhost location of README.

Please see #404 😃

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/409)

### CODE REVIEW

**Comment by justin808** [comment]
@tjnet this line should be configuring port 3000:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/8a6c8aa2e3b7ae5b08b0a9744fb3a63a2fe0f002/config/puma.rb#L12

Are you sure you don't have PORT defined in your environment to be 5000?

FWIW, I also define PORT in my environment to be 3000.

The default port for foreman to use with Rails is 5000.

**Comment by tjnet** [comment]
> Are you sure you don't have PORT defined in your environment to be 5000?

No, I don't have.

>FWIW, I also define PORT in my environment to be 3000.

oh... I think that newbie can not notice this .
It might be better to write this 😈

**Comment by justin808** [comment]
I'm not clear why you're getting port 5000 when we configure the port to be 3000 in the puma file.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/409#-:-KpNC5QOOOY2kV8ThFZn:b-87h5xh)*

**Comment by tjnet** [comment]
>FWIW, I also define PORT in my environment to be 3000.

I couldn't notice this is needed.

**Pull request closed without merging**
