### PR TITLE
Update Rails, Webpack, webpacker and misc dependencies

### PR DESCRIPTION
**Pull request by gscarv13**
#### This PR focus on updating the following:

- Rails to version 6.1.4
- Webpack, `webpacker` and its configurations
- `react-intl` to the latest version
- Procfile according using [react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh](https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh) as reference

This solves #488 issue.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490)

### CODE REVIEW

**Review by justin808 — CHANGES_REQUESTED** [review]
fix the action cable issue

look for upgrade things related to action cable

> Reviewed 73 of 73 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490#-:-MsqcFoMClPTQEILP6PG:b-54vidr)* status: all files reviewed, 1 unresolved discussion (waiting on @gscarv13)

___
*[app/views/pages/index.html.erb, line 14 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490#-Msqb2z9A4mOHLGOqD9I:-Msqb2z9A4mOHLGOqD9J:b-t4se3z) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/2c1f211bc0b18365d8a8ddf0c83fd4c672ad5d8b/app/views/pages/index.html.erb#L14)):*
> ```erb
> 
> 
> <%= react_component('RouterApp', id: "RouterApp-react-component-0", prerender: false) %>
> ```

this should not change to false

**Review by gscarv13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490)* status: 69 of 73 files reviewed, 1 unresolved discussion (waiting on @justin808)

___
*[app/views/pages/index.html.erb, line 14 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490#-Msqb2z9A4mOHLGOqD9I:-Mt3Eq_70570IRnjyHT6:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/2c1f211bc0b18365d8a8ddf0c83fd4c672ad5d8b/app/views/pages/index.html.erb#L14)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this should not change to false
</blockquote></details>

Done.

**Review by justin808 — COMMENTED** [review]
LGTM. You guys can merge.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/490#-:-Mt4pD_OErsGHtN_cSmF:b-oyz6tq)* status: all files reviewed, 1 unresolved discussion (waiting on @justin808)

**Comment by justin808** [comment]
@Judahmeek please merge once CI passes.

**Review by justin808 — APPROVED** [review]

**Pull request merged**
