### PR TITLE
Fixed libraryTarget key spelling, since it's critical!

### PR DESCRIPTION
**Pull request by kodemunki**
See https://webpack.github.io/docs/configuration.html#output-librarytarget

### CODE REVIEW

**Comment by justin808** [comment]
@kodemunki Thanks! 

@alexfedoseev, @samnang, how did this work being misspelled?  I'm going to look into this now.

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/pull/48

**Comment by justin808** [comment]
@kodemunki Please let me know if you want to update your PR to reflect that, and I'l merge, or else I'll make a new branch within the day to do this. The misspelling did not matter since we're using the globals syntax for server rendering.

**Comment by kodemunki** [comment]
@justin808 thanks for looking into this, I was wondering how it was working too!

**Comment by justin808** [comment]
#109 is taking care of this. Thanks @kodemunki.

**Pull request closed without merging**
