### PR TITLE
Update webpack to 3.4.1

### PR DESCRIPTION
**Pull request by alexeyMohnatkin**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/415)

### CODE REVIEW

**Comment by justin808** [comment]
please update the branch to the latest on master and I’ll merge.

**Comment by justin808** [comment]
@alexeyMohnatkin should this be merged? The CI fails.

**Comment by alexeyMohnatkin** [comment]
@justin808 sorry, I thought it was merged. Did you see errors? 
```
error react-webpack-rails-tutorial@2.0.0: The engine "node" is incompatible with this module. Expected version "7.8.0".
error react-webpack-rails-tutorial@2.0.0: The engine "yarn" is incompatible with this module. Expected version "0.22.0".
```
I don't think that my pr caused this errors
here you define engines
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/package.json#L6-L10
but in travis.yml versions are not locked
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/.travis.yml#L28-L30

**Comment by alexeyMohnatkin** [comment]
`yarn --ignore-engines` may help
What do you think?

**Comment by justin808** [comment]
@alexeyMohnatkin @Judahmeek what's the recommendation?

@alexeyMohnatkin At the min, please rebase your PR on top of master.

**Comment by alexeyMohnatkin** [comment]
@justin808 the right way is to lock dependencies in `travis.yml` too

**Comment by Judahmeek** [comment]
I hate to say this, but I think https://github.com/shakacode/react-webpack-rails-tutorial/pull/421/files#diff-52dbbf94d5c54b68c0cad0702ba94a96R99 supersedes this PR. I addressed the engine conflict by expanding the engine constraints.

**Comment by justin808** [comment]
@Judahmeek should we close this one?

**Comment by Judahmeek** [comment]
Yes. Thanks for your efforts, @alexeyMohnatkin.

**Pull request closed without merging**
