### PR TITLE
Removed and replaced no longer available repo

### PR DESCRIPTION
**Pull request by chunky123**
The old repo doesn't exist anymore, so I think replacing it with the original source makes sense here. Worked fine with my heroku deployment

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/400)

### CODE REVIEW

**Comment by justin808** [comment]
@Judahmeek please take a look at this one when you have a minute.

**Comment by justin808** [comment]
@judahmeek or @conturbo or @udovenko can you guys check on this one?

**Comment by justin808** [comment]
@chunky123 I'm not sure why your branch is not passing CI.

**Comment by chunky123** [comment]
Neither am I. Literally just a copy change :(

**Comment by justin808** [comment]
@chunky123 In the past, this has happened from using '^' in npm files (package.json) and '~' in Ruby files.

**Comment by justin808** [comment]
Thanks @chunky123.

**Pull request merged**
