### PR TITLE
Show errors on the "Simple React" page.

### LINKED ISSUE #295: Demo App Server Error
From @Undistraction
With the demo app here: [http://www.reactrails.com/?](http://www.reactrails.com/? ) the following message is displayed if a name is entered but no text is entered:

> Your comment was not saved! A server error prevented your comment from being saved. Please try again.

If a value for text is required, this should be indicated and a more appropriate error message should be displayed as it initially appears the app is broken.

-----

I agree.

@undistraction, want to submit a PR?

### PR DESCRIPTION
**Pull request by AlexKVal**
Partially resolves #295

`Simple React` page.

I probably will try to fix other pages as well.
(Later. When I feel myself less sick.)

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/321)

### CODE REVIEW

**Comment by justin808** [comment]
@alexkval Looks outstanding.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5SPQuqKSx3TtaTkCj:-KP5SPQuqKSx3TtaTkCk:b-q0aemn) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L19)):*
> ```JSX
>   if (error) {
>     const errorData = (error && error.response && error.response.data) || {};
>     return (propName in errorData) ? 'error' : 'success';
> ```

I've hardly ever used the `in` operator in JS. @alexfedoseev should we be using it more? I usually use `_.has`: https://lodash.com/docs#has

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 132 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5T9qJJJmN1l6akPAt:-KP5T9qJJJmN1l6akPAu:b-g9roee) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L132)):*
> ```JSX
>             disabled={this.props.isSaving}
>             hasFeedback={true}
>             bsStyle={bsStyleFor('author', this.props.error)}
> ```

Nice to be adding this!

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 145 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5TVVlXyJmmwH-m2fq:-KP5TVVlXyJmmwH-m2fr:bakm2e0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L145)):*
> ```JSX
>             disabled={this.props.isSaving}
>             hasFeedback={true}
>             bsStyle={bsStyleFor('text', this.props.error)}
> ```

https://github.com/react-bootstrap/react-bootstrap/pull/1765

https://github.com/react-bootstrap/react-bootstrap/issues/1826

Should we change Input to something else?

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 254 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5UPWbLe7s5MuZqDoE:-KP5UPWbLe7s5MuZqDoF:bb70w76) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L254)):*
> ```JSX
>     const errorElements = _.transform(errorData, (result, errorText, errorFor) => {
>       result.push(<li key={errorFor}><b>{_.upperFirst(errorFor)}:</b> {errorText}</li>);
>     }, []);
> ```

Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-:-KP5U_K8T8js593VTJY_:b61y40h)*

**Comment by AlexKVal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5SPQuqKSx3TtaTkCj:-KPDG2Yu9uyft1AeqbDb:b-2ncjdv) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L19)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> I've hardly ever used the `in` operator in JS. @alexfedoseev should we be using it more? I usually use `_.has`: https://lodash.com/docs#has
</details>
My motivations:
The project already uses ES6 transpiler hence it is OK to use "in".
"_.has" is one more dependency.
--
I rewrite it if it is more preferable.

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 145 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5TVVlXyJmmwH-m2fq:-KPDHzvgxm5U4lqBoZSQ:btyb21g) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L145)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> https://github.com/react-bootstrap/react-bootstrap/pull/1765
> 
> https://github.com/react-bootstrap/react-bootstrap/issues/1826
> 
> Should we change Input to something else?
</details>
I wanted to postpone RB dependency updating to another PR and decided to solve the task at hand with as minimum side-effects as it is possible :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321)*

**Comment by alexfedoseev** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 19 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5SPQuqKSx3TtaTkCj:-KPDLJVG-JZl2SI7Dah2:b-wjg92z) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L19)):*
<details><summary><i>Previously, AlexKVal (Alexander Shemetovsky) wrote…</i></summary>
> My motivations:
> The project already uses ES6 transpiler hence it is OK to use "in".
> "_.has" is one more dependency.
> --
> I rewrite it if it is more preferable.
</details>
Between native and lib ways I always choose native, so my opinion: as `in` operator is standard, it absolutely legit to use it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321)*

**Comment by AlexKVal** [comment]
I've added the fix for the "React Demo" page.
Now it works too.

Now I will rewind the branch to master to resolve current conflicts.

**Comment by AlexKVal** [comment]
I've rebased the PR onto the latest master.

Should I update `React-Bootstrap` dependency (and with it all the form elements) within this PR
or new one ?
If in the new one, then I'll do it after this PR has merged.

🍒

**Comment by justin808** [comment]
@alexkval The key thing we need is a capybara test that verifies this across the page. If we had that test, we would have caught this issue long ago.

Otherwise, looking fabulous!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx, line 145 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-KP5TVVlXyJmmwH-m2fq:-KPEbyM_kHoIFCFx6E14:bf9w6sk) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8e984173a582671a016f16d39a3c144d1c34bcd8/client/app/bundles/comments/components/CommentBox/CommentForm/CommentForm.jsx#L145)):*
<details><summary><i>Previously, AlexKVal (Alexander Shemetovsky) wrote…</i></summary>
> I wanted to postpone RB dependency updating to another PR and decided to solve the task at hand with as minimum side-effects as it is possible :smile: 
</details>
@alexkval, @dylangrafmyre and @robwise would appreciate this philosophy of keeping PRs focused! Thank you for this insight! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-:-KPEc9s8VLn-Q8SDDylJ:bef4a9z)*

**Comment by AlexKVal** [comment]
> @alexkval The key thing we need is a capybara test

Then I'll learn `Capybara` and add tests with it.

**Comment by AlexKVal** [comment]
I added tests.
They not only check for validation errors displaying,
but what should happen after a consequent successful submitting as well.

**Comment by justin808** [comment]
:lgtm_strong: 

Fabulous!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/321#-:-KPfW_stvUdQZOqVIEYe:bh8eckf)*

**Pull request merged**
