### PR TITLE
Add travis.yml file for Travis-CI build

### PR DESCRIPTION
**Pull request by dylangrafmyre**
Create travis.yml file to verify working build process on CI platform.

### CODE REVIEW

**Comment by justin808** [comment]
@dylangrafmyre If you verified this work, please merge it and try it out. It won't break anything else.

**Comment by samnang** [comment]
Should we have build status's badge on in readme as well?

**Comment by justin808** [comment]
That would be great, for all the projects. We need a set of files in the docs folder on the setup for this.

**Comment by dylangrafmyre** [comment]
Yes we will add that and https://coveralls.io/

**Pull request merged**
