### PR TITLE
Updating ruby version and gem versions

### PR DESCRIPTION
**Pull request by tmobaird**
References #382.

@justin808 here's the PR for updating the ruby version and gem versions. I chose to split the dependency updates up into two different PRs (one for each Ruby and JS) to help minimize any problems that are encountered.

The important stuff: **I updated the ruby version to 2.4.1 and updated the gem versions.**

The app is running just fine for me locally, and all the specs are passing as well. It should build just fine on travis, as long as ruby 2.4.1 is available on Travis's rvm (I believe it should be).

Feel free to let me know if there are any other changes you want me to make.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/383)

### CODE REVIEW

**Comment by tmobaird** [comment]
Looks like the build failed because of the style checks from Rubocop. It appears the upgraded ruby version/rubocop version triggered new style check offenses. @justin808 thoughts?

**Comment by justin808** [comment]
Please try to address the rubocop issues.

`rubocop -a` FTW --> autofix

**Comment by tmobaird** [comment]
@justin808 this should be good to go now. Besides updating the ruby version and gems, I had to update some of the source files, as well as the rubocop config, to fix new rubocop warnings that occurred after the version update. 

Let me know if there's anything else you'd like me to change!

**Comment by justin808** [comment]
Let's update the npm libraries now! Thanks @tmobaird!

**Pull request merged**
