### PR TITLE
updated from therubyracer to mini_racer

### PR DESCRIPTION
**Pull request by dzirtusss**
Updated from therubyracer to mini_racer #309

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/311)

### CODE REVIEW

**Comment by dzirtusss** [comment]
1. Not sure about removing that info from README.md
2. Didn't change anything in react_on_rails folder

**Comment by justin808** [comment]
:lgtm:

I already merged the mini_racer gem as I didn't see this PR.

Please rebase on top of master, and we'll merge the README.md change.

Thanks!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/311#-:-KO3_rqZejb6AQ5sfDEx:-1571249474)*

**Comment by dzirtusss** [comment]
Done, please look, first time rebasing in git

**Comment by justin808** [comment]
@dzirtusss Thank you so much!

**Pull request merged**
