### PR TITLE
Add redis-server info to README

### LINKED ISSUE #358: Is Redis missing from Foreman Procfile?
I'm just trying to get the tutorial to run on my machine to play with it. I did foreman start -f Procfile.hot then loaded http://localhost:5000/ and posted a comment. Then I saw this:

Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
16:48:13 rails.1               | /Users/mark/.rvm/gems/ruby-2.4.0@test-react-on-rails/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)

I'm guessing action_cable needs Redis and it wasn't started?

### PR DESCRIPTION
**Pull request by adekbadek**
resolves #358

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/366)

### CODE REVIEW

**Comment by justin808** [comment]
@adekbadek I think this would be best as a doc change as I've been running redis for all my apps for many years, via the brew install.

**Comment by justin808** [comment]
@adekbadek please remove all changes except the README.md.

**Comment by adekbadek** [comment]
@justin808 done

**Comment by justin808** [comment]
Thanks @adekbadek.

**Pull request merged**
