### PR TITLE
Update application.js

### PR DESCRIPTION
**Pull request by justin808**

### CODE REVIEW

**Comment by robwise** [comment]
Just as a note: we determined this was not necessary because the shim is already being included in the webpack, so we don't need to also include it in sprockets.

**Comment by hisapy** [comment]
Based on this merge, would it be ok to remove **gem 'es5-shim-rails'** from Gemfile?

**Comment by robwise** [comment]
@hisapy Yes, good point, I'm making a new PR to incorporate that. https://github.com/shakacode/react-webpack-rails-tutorial/pull/132

**Comment by hisapy** [comment]
Thx for the quick response @robwise

**Pull request merged**
