### PR TITLE
Update Linters

### PR DESCRIPTION
**Pull request by gscarv13**
This PR contains: 

- Updated ESLint and its configurations
- Updated rubocop and its configurations
- Updated Babel
- Add Prettier

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491)

### CODE REVIEW

**Review by Judahmeek — CHANGES_REQUESTED** [review]
A lot of work was done there! Hopefully, my suggestions won't be too difficult to implement.

> Reviewed 110 of 110 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-:-Mt4gAz2ARSsP5ZF4xWl:boa4dui)* status: all files reviewed, 6 unresolved discussions (waiting on @gscarv13 and @justin808)

___
*[.eslintrc, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4fRGo95t_LW7tLaf6:-Mt4fRGo95t_LW7tLaf7:b-mbfm8r) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/.eslintrc#L7)):*
> ```
>   - plugin:jsx-a11y/recommended
>   - prettier
> ```

Let's add `- prettier/react` like the RoR & RoR Pro repos have.
___
*[.rubocop.yml, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4WDuM-40kQLDEczU-:-Mt4WDuM-40kQLDEczU0:b-hpph5x) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/.rubocop.yml#L7)):*
> ```YAML
>   - rubocop-performance
>   - rubocop-rspec
> ```

Let's add `rubocop-rails`
___
*[Gemfile, line 109 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4XY7IARJn-uGzgMjh:-Mt4XY7JDvzGi5r1l2Wv:b-9p6ixm) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/Gemfile#L109)):*
> ```Ruby
> end
> 
> gem "rubocop-performance", "~> 1.13"
> ```

This should be moved up to be with the other rubocop gems
___
*[client/app/bundles/comments/components/CommentBox/CommentBox.jsx, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4_Ffs7UYUWhQ_4gcO:-Mt4_Fft6uabuqm6ZCLz:bsx3qva) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/client/app/bundles/comments/components/CommentBox/CommentBox.jsx#L7)):*
> ```JavaScript
> import _ from 'lodash';
> import { injectIntl, intlShape } from 'react-intl';
> import BaseComponent from '../../../../libs/components/BaseComponent.jsx';
> ```

This isn't as readable as before.

Let's try using [the eslint-plugin-import webpack resolver](https://stackoverflow.com/a/54414205/5241481)

Although that's going to have to be configured to use `config/webpack/development` somehow. You & I might need to pair on this.
___
*[client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx, line 1 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4cQ6V5RyY7V4vhuZ4:-Mt4cQ6V5RyY7V4vhuZ5:b-sqq20h) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L1)):*
> ```JavaScript
> // eslint-disable-next-line max-classes-per-file
> ```

Probably best to actually follow this rule & split out any extra classes into their own file.
___
*[client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx, line 14 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4dR3n6ZwvaggShvUf:-Mt4dR3o2D70rVMnFnBj:b-z898p2) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L14)):*
> ```JavaScript
> 
> import CommentForm from '../CommentBox/CommentForm/CommentForm.jsx';
> import CommentList from '../CommentBox/CommentList/CommentList.jsx';
> ```

I think we can avoid having to add the `jsx` file extension by adding `jsx` to the [import/extensions configuration for eslint-plugin-imports](https://github.com/import-js/eslint-plugin-import#importextensions).

Actually, I think adding `prettier/react` to the `.eslintrc` will resolve this issue.

**Review by justin808 — CHANGES_REQUESTED** [review]
Generally OK. We need to separate auto-fixes from configuration changes. I did not review everything.

Also, we can't be spending all our time on such updates. They don't add that much business value.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-:-Mt4osLO8ccX1RyJt2dx:b-svs8v5)* status: all files reviewed, 7 unresolved discussions (waiting on @gscarv13)

___
*[.eslintignore, line 6 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4oasH3KUYKfUFHSas:-Mt4oasH3KUYKfUFHSat:bdn57ho) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/.eslintignore#L6)):*
> ```ignore
> client/app/libs/i18n/translations.js
> client/app/libs/i18n/default.js
> postcss.config.js
> ```

why is this excluded?

**Comment by justin808** [comment]
@Judahmeek @gscarv13 close this or update?

**Comment by justin808** [comment]
@gscarv13 any update on this?

**Comment by gscarv13** [comment]
> @gscarv13 any update on this?

I'll be working on this

**Review by justin808 — COMMENTED** [review]
LGTM

Ready for merge?

> Reviewed 41 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-:-MwjnHjz4PP05VWz15gO:b-td5zyk)* status: all files reviewed, 7 unresolved discussions (waiting on @gscarv13)

**Review by justin808 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-:-MwjnL0G1N9cDNjjK2il:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @gscarv13)

**Review by gscarv13 — COMMENTED** [review]
If @judahmeek don't need me to fix anything then yes 

> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-:-Mx1Po6q8zVmRw_qJ-Aq:b-nuzqro)* status: all files reviewed, 7 unresolved discussions (waiting on @gscarv13 and @Judahmeek)

___
*[.eslintrc, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4fRGo95t_LW7tLaf6:-MwguKha68CKaLsUFcoY:b-6y7a1l) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/.eslintrc#L7)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

Let's add `- prettier/react` like the RoR & RoR Pro repos have.
</blockquote></details>

`prettier/react` has been merged into `prettier` in eslint-config-prettier 8.0.0 which is the version currently being used here. 
more info: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

Should we downgrade `eslint-config-prettier`?
___
*[Gemfile, line 109 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/491#-Mt4XY7IARJn-uGzgMjh:-Mwgzw0w229xYCm0nveI:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/386470ffb2968b93e0c19990b001cc06409b0d39/Gemfile#L109)):*
<details><summary><i>Previously, Judahmeek (Judah Meek) wrote…</i></summary><blockquote>

This should be moved up to be with the other rubocop gems
</blockquote></details>

Done.

**Comment by justin808** [comment]
Thanks @gscarv13!

**Pull request merged**
