### PR TITLE
Added stimulus example - update

### PR DESCRIPTION
**Pull request by ahangarha**
Updating #492

- - -
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/533)

### CODE REVIEW

**Comment by ahangarha** [comment]
Despite passing all except one test in [this CI run](https://github.com/shakacode/react-webpack-rails-tutorial/actions/runs/5575934932/jobs/10186662180), tests for turbo are not correct.

**Comment by ahangarha** [comment]
Note:
Though tests are getting passed, there are some errors and warnings in the browser console.

**Comment by ahangarha** [comment]
@justin808 @Judahmeek 
Do you have any more concerns about this PR?

**Comment by justin808** [comment]
Looks OK to me. @Judahmeek can you run this and check?

**Comment by justin808** [comment]
`flash of unstyled content` 

and lots of console messages

image

**Comment by ahangarha** [comment]
@justin808 For flashing I opened and issue (#545) to work on it separately 
Regarding the error in the browswer console, we have it in master branch also.

I believe it is resolved in #529 PR.

**Comment by justin808** [comment]
@ahangarha please address my concerns in follow up prs

**Comment by ahangarha** [comment]
@justin808 They are fixed in the other PRs.
I aim to resolve all issues before starting anything new in this project. So we start over from solid ground.

**Pull request merged**
