### PR TITLE
Initialize dockerized version

### LINKED ISSUE #331: Demonstrate this in a docker container
It would be great if this project has a Dockerfile
It is a pretty complete application that a lot of people could learn from

### PR DESCRIPTION
**Pull request by thetonyrom**
Resolves #331

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/456)

### CODE REVIEW

**Comment by justin808** [comment]
@thetonyrom This looks great. However, we really should take out the QT dependency and remove https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Gemfile#L97...

There are a few other references to capybara-webkit in the repo.

We're actually going beyond headless chrome and using cypress.io for testing.

**Comment by thetonyrom** [comment]
@justin808 I see your point. I have a pretty busy week, probably, I'll update the PR in the coming weekend.

**Comment by thetonyrom** [comment]
@justin808 I've updated the PR, have a look

**Comment by justin808** [comment]
I'm about to make a new PR that fixes your CI issue. rebase on top of that and push again, please.

**Comment by justin808** [comment]
@thetonyrom Can you rebase on top of master and push.

**Comment by thetonyrom** [comment]
Done

**Comment by thetonyrom** [comment]
Hey @justin808 . Let's finish it! :) Let me know if anything.

**Pull request closed without merging**
