### PR TITLE
Installation more portable and smooth. Closes #495

### LINKED ISSUE #495: Installation and first use should be smoother
After installling and running on adJ 7.1 and Ubuntu 21.10  (see https://github.com/vtamara/react-webpack-rails-tutorial/wiki/Using-on-adJ-(distribution-of-OpenBSD)-7.1a1 and https://github.com/vtamara/react-webpack-rails-tutorial/wiki/Using-on-Ubuntu-21.10 ) I have some suggestions to make the installation smoother:

* Documentation of the installation steps should be precise
* Documentation and code should be more portable.
* IMHO, avoid unncessary installation steps,  e.g running `foreman` requires the addtional step of installing globally the gem `foreman`, better `bundle exec foreman`
* Use the simplest tools that help to understand the concepts of `react_on_rails`, for example `node` instead of `mini_racer` (due to difficulties with versions of `libv8`, `ruby-libv8`, `mini_racer` and different operating systems  --even on Ubuntu--, the gem `mini_racer` uses to be problematic, although it is good for production code where speed is priority as could be stated as commentary in the Gemfile).
* In case that a user forks, changes  and commits his/her changes to the repository, that he/she will not publish the user or passwords by mistake in `config/database.yml`
* Updated gems and npm packages

### PR DESCRIPTION
**Pull request by vtamara**
* Installation more portable: tested on Ubuntu 21.10 and adJ/OpenBSD 7.1a1
* Unnecessary or outdated gems removed: `mini_racer`, `sass-rails`
* Gems and packages updated. Required gem after update added `net-smtp`
* Using `.env` to manage user and password in environment variables (suggested by https://12factor.net/ )
* Ready to run in recent platforms with more on less standard configuration
* Different name for databases in development, tests  and production
* Documentation of installation udpated and reviewed, notes about specific platforms removed
* In documentation removed almost all sections about non-existing Procfiles

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496)

### CODE REVIEW

**Review by justin808 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496)* status: all files reviewed, 11 unresolved discussions (waiting on @vtamara)

___
*[.env.template, line 2 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOTw-3T3GpQjUuK_N:-MzEOTw-3T3GpQjUuK_O:b-47rtbz) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/.env.template#L2)):*
> ```
> DB_USER=pguser
> DB_PASSWORD=pgpass
> ```

MacOS users generally don't need this, so this is a bit confusing.
___
*[Gemfile, line 46 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOov04J9za-bu5gaA:-MzEOov04J9za-bu5gaB:b-q3dal0) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/7feaf746295686f55efde8802039280bdfb25130/Gemfile#L46)):*
> ```Ruby
> # See https://github.com/sstephenson/execjs#readme for more supported runtimes
> # mini_racer is probably faster than therubyracer
> gem "mini_racer", platforms: :ruby
> ```

why are you removing mini_racer? Wouldn't we need something to replace it?
___
*[Gemfile, line 54 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOuCB4V4fSIwa8d9M:-MzEOuCB4V4fSIwa8d9N:b-a2z2xg) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/Gemfile#L54)):*
> ```Ruby
> 
> # To keep your database user and password in .env
> gem 'dotenv-rails'
> ```

What's wrong with just setting some ENV values?

or using a .envrc?

I like dotenv-rails, but I don't see us having enough reason to add this dependency.
___
*[Procfile.dev, line 3 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPCZK-b2-tLLCrboR:-MzEPCZK-b2-tLLCrboS:b-chrpkp) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/Procfile.dev#L3)):*
> ```
> # Procfile for development using HMR
> # You can run these commands in separate shells
> # redis should be running
> ```

good

@judahmeek @gscarv13 this should never have been added. 
___
*[package.json, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPJY40vG8CohLpdEA:-MzEPJY40vG8CohLpdEB:b4po0sj) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/package.json#L7)):*
> ```JSON
>   "engines": {
>     "node": "^16.13.2",
>     "yarn": "^1.22.10"
> ```

why downgrade yarn?

I think the `^` is god.
___
*[README.md, line 143 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPuJ-A8CL-6gmafu1:-MzEPuJ-A8CL-6gmafu2:b3g9fkw) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L143)):*
> ```Markdown
> 1. Check that you're using the right version of node. Run `nvm list` to check. Use 16.0 or greater.
> 1. Check that you have Postgres installed. Run `which postgres` to check. Use 9.4 or greater.
> 1. Install redis
> ```

I really don't like telling devs how to install redis, yarn, node, ruby, etc. as there are many ways to do this and none are better than others. By us telling devs in this project, some devs will be unsure if they need to do it this way or some other way. 

For example, I just started using `asdf` with my new Mac. I'm not sure if I really like it better, however.
___
*[README.md, line 206 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQPZGDAxlK0MI6qOc:-MzEQPZGDAxlK0MI6qOd:b-u9pa6i) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L206)):*
> ```Markdown
>    yarn build
>    cd ../..
>    ```
> ```

I don't understand why you'd have these steps. I guess the other PR removes this.
___
*[README.md, line 213 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQWj077-fktWZ48qp:-MzEQWj077-fktWZ48qq:byvrxwp) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L213)):*
> ```Markdown
>    ```
>    and edit `.env` to set your PostgreSQL user in `DB_USER`, its password
>    in `DB_PASSWORD`, and if needed PostgreSQL host/path in `DB_HOST`
> ```

This part above is confusing to most Mac Rails devs
___
*[README.md, line 219 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQdOaAS7cz0_lWwor:-MzEQdOaAS7cz0_lWwos:b-6sasne) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L219)):*
> ```Markdown
> 
>    ```sh
>    createdb -h /var/www/var/run/postgresql -U pguser react-webpack-rails-tutorial
> ```

this user will need to be in the .env file, right?
___
*[README.md, line 319 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQtfp5k4J0m3sx73L:-MzEQtfp5k4J0m3sx73M:b5vzv7r) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L319)):*
> ```Markdown
> ```
> 
> 1. [`Procfile.dev`](Procfile.dev): Starts Redis, Rails and Webpack Dev Server with Hot Reloading.
> ```

Procfiles should not start redis.
___
*[config/database.yml, line 33 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzERENcCMGmGVTN_uSH:-MzERENcCMGmGVTN_uSI:b-2gpdza) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/config/database.yml#L33)):*
> ```YAML
>   username: <%= ENV.fetch('DB_USER', '') %>
>   password: <%= ENV.fetch('DB_PASSWORD', '') %>
>   host: <%= ENV.fetch('DB_HOST', '') %>
> ```

Would this work? and no need for dotenv-rails?

```yml
    host: <%= ENV["DB_HOST"] || "localhost" %>
    password: <%= ENV["DB_PASSWORD"] %>
    port: <%= ENV["DB_PORT"] || "5432" %>
    username: <%= ENV["DB_USER"] %>
``
```

**Comment by vtamara** [comment]
Thanks for feedback

> why are you removing mini_racer? Wouldn't we need something to replace it?

rails uses node.js.  I see many people having trouble with `mini_racer`, for this example I had trouble with it in Ubuntu and adJ, see screenshots at <https://github.com/vtamara/react-webpack-rails-tutorial/wiki/Using-on-adJ-(distribution-of-OpenBSD)-7.1a1> and <https://github.com/vtamara/react-webpack-rails-tutorial/wiki/Using-on-Ubuntu-21.10>

> I don't understand why you'd have these steps. I guess the other PR removes this.

If I dont' do these steps when I run it produces:
```
ERROR in ./node_modules/bootstrap-loader/loader.js 2:0-61                                                                                
Module not found: Error: Can't resolve './lib/bootstrap.loader' in ...
```
I thinks this happens because `package.json` is not using the npm package of `bootstrap-loader` (which would have the directory `lib` with the result of building) but it has a github repository that doesn't have the `lib` directory:
```
"bootstrap-loader": "judahmeek/bootstrap-loader#judahmeek/webpack-5",
```

If you accept #498, this will not be needed.


> Would this work? and no need for dotenv-rails?

Yes it works without `dotenv-rails`, because extending `ENV` with `fetch` comes from rails.

The example you did would become:
```
host: <%= ENV.fetch("DB_HOST",  "localhost") %>
password: <%= ENV.fetch("DB_PASSWORD", nil) %>
port: <%= ENV.fetch("DB_PORT",  "5432") %>
username: <%= ENV.fetch("DB_USER", nil) %>
```

However leaving host in "" works fine in Ubuntu, and I guess it will work fine in MacOS.


I addressed the other comments by improving the PR with new commits.

Thank you.

**Comment by justin808** [comment]
@vtamara are you 100% sure that ActiveSupport loads before database.yml?

Startup time in rails requires care in what can and can't be used.

**Comment by vtamara** [comment]
> 

Yes, not only because the patch I sent is working, but because I did the following experiment, with this repository:

1. I cloned the rails repository to a local directory and switched to branch 6-1-stable (since this application is using '~> 6.1.4' in the Gemfile).
1. I changed the Gemfile of this application replacing
    ```gem "rails", "~> 6.1.4"```
   for
    ```gem "rails", path: "../rails"```
   and run `bundle`
1. In the sources of rails I looked where it was reading `database.yml` and found the function `database_configuration`,  I set a breakpoint there in line https://github.com/rails/rails/blob/d38ff07a39c98f5db2b15ca3a51acee48c972205/railties/lib/rails/application/configuration.rb#L281
1. I started the application and it stoped in my breakpoint, I did `ENV.fetch('DB_USER')` and it worked, besides checking the backtrace there it is:

```
--> #0  Rails::Application::Configuration.database_configuration at /home/vtamara/comp/rails/tmp/rails/railties/lib/rails/application/configuration.rb:282          #1  block (2 levels) in block (2 levels) in <class:Railtie> at /home/vtamara/comp/rails/tmp/rails/activerecord/lib/active_record/railtie.rb:221             
    ͱ-- #2  Module.class_eval(*args) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/lazy_load_hooks.rb:71                               
    #3  block in ActiveSupport::LazyLoadHooks.block in execute_hook(name#Symbol, base#Class, options#Hash, block#Proc) at /home/vtamara/comp/rails/tmp/rails/act
ivesupport/lib/active_support/lazy_load_hooks.rb:71                                                                                                             
    #4  ActiveSupport::LazyLoadHooks.with_execution_control(name#Symbol, block#Proc, once#NilClass) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/lazy_load_hooks.rb:61                                                                                                                                
    #5  ActiveSupport::LazyLoadHooks.execute_hook(name#Symbol, base#Class, options#Hash, block#Proc) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/act
ive_support/lazy_load_hooks.rb:66                                                                                                                               
    #6  block in ActiveSupport::LazyLoadHooks.block in run_load_hooks(name#Symbol, base#Class) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_su
pport/lazy_load_hooks.rb:52                                                                                                                                     
    ͱ-- #7  Array.each at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/lazy_load_hooks.rb:51                                                 #8  ActiveSupport::LazyLoadHooks.run_load_hooks(name#Symbol, base#Class) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/lazy_load_ho
oks.rb:51                                                                                                                                                       
    #9  <module:ActiveRecord> at /home/vtamara/comp/rails/tmp/rails/activerecord/lib/active_record/base.rb:315                                                      #10 <top (required)> at /home/vtamara/comp/rails/tmp/rails/activerecord/lib/active_record/base.rb:15                                                        
    ͱ-- #11 Kernel.require at /var/www/bundler/ruby/3.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35                                                           
    #12 Object.require(path#String) at /var/www/bundler/ruby/3.1/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35                                     
    #13 #<Class:ActiveRecord::QueryCache>.run at /home/vtamara/comp/rails/tmp/rails/activerecord/lib/active_record/query_cache.rb:31        
    #14 ActiveSupport::ExecutionWrapper::RunHook.before(target##<Class:0x000002906ff47ef8>) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/execution_wrapper.rb:28
    #15 block in ActiveSupport::Callbacks::CallTemplate.block in make_lambda at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/callbacks.rb
:427                                                                                                                                                                #16 block (2 levels) in #<Class:ActiveSupport::Callbacks::Filters::Before>.block (2 levels) in halting(callback_sequence#ActiveSupport::Callbacks::CallbackS
equence, user_callback#Proc, halted_lambda#Proc, filter#ActiveSupport::ExecutionWrapper::RunHook, name#Symbol) at /home/vtamara/comp/rails/tmp/rails/activesuppo
rt/lib/active_support/callbacks.rb:198                                                                                                                          
    #17 block (2 levels) in ActiveSupport::Callbacks::CallbackChain.block (2 levels) in default_terminator at /home/vtamara/comp/rails/tmp/rails/activesupport/l
ib/active_support/callbacks.rb:604                                                                                                                                  ͱ-- #18 Kernel.catch(*args) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/callbacks.rb:603                                         
    #19 block in ActiveSupport::Callbacks::CallbackChain.block in default_terminator at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/call
backs.rb:603                                                                                                                                                    
    #20 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(callback_sequence#ActiveSupport::Callbacks::CallbackSequence, user_callback
#Proc, halted_lambda#Proc, filter#ActiveSupport::ExecutionWrapper::RunHook, name#Symbol) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/
callbacks.rb:199                                                                                                                                                    #21 block in ActiveSupport::Callbacks::CallbackSequence.block in invoke_before(arg#ActiveSupport::Callbacks::Filters::Environment) at /home/vtamara/comp/rai
ls/tmp/rails/activesupport/lib/active_support/callbacks.rb:512                                                                                                  
    ͱ-- #22 Array.each at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/callbacks.rb:512                                                      #23 ActiveSupport::Callbacks::CallbackSequence.invoke_before(arg#ActiveSupport::Callbacks::Filters::Environment) at /home/vtamara/comp/rails/tmp/rails/activ
esupport/lib/active_support/callbacks.rb:512                                                                                                                    
    #24 ActiveSupport::Callbacks.run_callbacks(kind#Symbol) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/callbacks.rb:105
    #25 ActiveSupport::ExecutionWrapper.run! at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/execution_wrapper.rb:114
    #26 block in #<Class:ActiveSupport::ExecutionWrapper>.block in run!(reset#TrueClass) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/execution_wrapper.rb:77   
    #27 Kernel.tap at /home/vtamara/comp/rails/shaka/react-webpack-rails-tutorial/<internal:kernel>:90                                                          
    #28 #<Class:ActiveSupport::ExecutionWrapper>.run!(reset#TrueClass) at /home/vtamara/comp/rails/tmp/rails/activesupport/lib/active_support/execution_wrapper.rb:74                                                                                                                                                           
    #29 ActionDispatch::Executor.call(env#Hash) at /home/vtamara/comp/rails/tmp/rails/actionpack/lib/action_dispatch/middleware/executor.rb:12                  
    #30 ActionDispatch::Static.call(env#Hash) at /home/vtamara/comp/rails/tmp/rails/actionpack/lib/action_dispatch/middleware/static.rb:24                      
    #31 Rack::Sendfile.call(env#Hash) at /var/www/bundler/ruby/3.1/gems/rack-2.2.3/lib/rack/sendfile.rb:110                                                     
    #32 ActionDispatch::HostAuthorization.call(env#Hash) at /home/vtamara/comp/rails/tmp/rails/actionpack/lib/action_dispatch/middleware/host_authorization.rb:148                                                                                                                                                              
    #33 Webpacker::DevServerProxy.perform_request(env#Hash) at /var/www/bundler/ruby/3.1/gems/shakapacker-6.0.2/lib/webpacker/dev_server_proxy.rb:25            
    #34 Rack::Proxy.call(env#Hash) at /var/www/bundler/ruby/3.1/gems/rack-proxy-0.7.2/lib/rack/proxy.rb:67                                                      
    #35 Rails::Engine.call(env#Hash) at /home/vtamara/comp/rails/tmp/rails/railties/lib/rails/engine.rb:539                                                     
    #36 Puma::Configuration::ConfigMiddleware.call(env#Hash) at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/configuration.rb:252                         
    #37 block in Puma::Request.block in handle_request(client#Puma::Client, lines#Puma::IOBuffer, requests#Integer) at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/request.rb:77                                                                                                                                         
    #38 Puma::ThreadPool.with_force_shutdown at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/thread_pool.rb:340                                           
    #39 Puma::Request.handle_request(client#Puma::Client, lines#Puma::IOBuffer, requests#Integer) at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/request.rb:76                                                                                                                                                           
    #40 Puma::Server.process_client(client#Puma::Client, buffer#Puma::IOBuffer) at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/server.rb:441             
    #41 block in Puma::ThreadPool.block in spawn_thread at /var/www/bundler/ruby/3.1/gems/puma-5.6.2/lib/puma/thread_pool.rb:147       
```

As you can see loading that file is done by using methods of `ActiveSupport`  (It is interesting to notice that shakapacker is there very early in the initialization process in frame 33 with `Webpacker::DevServerProxy.perform_request(env#Hash)`.

**Review by vtamara — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496)* status: 5 of 12 files reviewed, 11 unresolved discussions (waiting on @gscarv13, @Judahmeek, and @justin808)

___
*[.env.template, line 2 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOTw-3T3GpQjUuK_N:-MzLZv9eA657B2Ad-yYT:b-9ucwm3) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/.env.template#L2)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

MacOS users generally don't need this, so this is a bit confusing.
</blockquote></details>

I removed `dotenv-rails` so MacOS user's don't need to copy and fill this, but this is useful in other OS and configurations (including production). If a MacOS user anyway uses this .env, this one with everything empty should work.
___
*[Gemfile, line 46 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOov04J9za-bu5gaA:-MzL_RNj4hMZc8kijPYq:btqu3zn) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/7feaf746295686f55efde8802039280bdfb25130/Gemfile#L46)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why are you removing mini_racer? Wouldn't we need something to replace it?
</blockquote></details>

rails uses node.js by default
___
*[Gemfile, line 54 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOuCB4V4fSIwa8d9M:-MzL_WYz55n0UEk5oPqc:bv6u4p8) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/Gemfile#L54)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

What's wrong with just setting some ENV values?

or using a .envrc?

I like dotenv-rails, but I don't see us having enough reason to add this dependency.
</blockquote></details>

Removed.  Users in other OS's or for example in production can do: `.env && bundle exec foreman start -i Procfile.dev`
___
*[Procfile.dev, line 3 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPCZK-b2-tLLCrboR:-MzL_pew2YSAXh2-7HN_:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/Procfile.dev#L3)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

good

@judahmeek @gscarv13 this should never have been added. 
</blockquote></details>

Done.
___
*[package.json, line 7 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPJY40vG8CohLpdEA:-MzL_rDU6yikHlVZol8b:b-896fix) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/package.json#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

why downgrade yarn?

I think the `^` is god.
</blockquote></details>

Done.
___
*[README.md, line 143 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEPuJ-A8CL-6gmafu1:-MzL_tXoCWOh-2bP-R3W:ba3dfob) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L143)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I really don't like telling devs how to install redis, yarn, node, ruby, etc. as there are many ways to do this and none are better than others. By us telling devs in this project, some devs will be unsure if they need to do it this way or some other way. 

For example, I just started using `asdf` with my new Mac. I'm not sure if I really like it better, however.
</blockquote></details>

Removed
___
*[README.md, line 206 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQPZGDAxlK0MI6qOc:-MzL_yWa-M1Hj5IvTuvk:b-9vmvgd) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L206)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I don't understand why you'd have these steps. I guess the other PR removes this.
</blockquote></details>

Required because in package.json there is a github repository for `bootstrap-loader` and that github repository doesn't have directory `lib`
___
*[README.md, line 213 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQWj077-fktWZ48qp:-MzLaG-Y35_sUi0z9jKV:b-binc19) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L213)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

This part above is confusing to most Mac Rails devs
</blockquote></details>

I started with "If you have special PostgreSQL user..." 
___
*[README.md, line 219 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQdOaAS7cz0_lWwor:-MzLaPczCfnw9t4XgFxq:b93l4wz) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L219)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

this user will need to be in the .env file, right?
</blockquote></details>

Right. Changed.
___
*[README.md, line 319 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEQtfp5k4J0m3sx73L:-MzLaTvV0bVLqaXXaP_O:b-sxqgnr) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/README.md#L319)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Procfiles should not start redis.
</blockquote></details>

Agreed. Changed.
___
*[config/database.yml, line 33 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzERENcCMGmGVTN_uSH:-MzLaZf42Ek60NOfL1oj:b-nyrnq8) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/config/database.yml#L33)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

Would this work? and no need for dotenv-rails?

```yml
    host: <%= ENV["DB_HOST"] || "localhost" %>
    password: <%= ENV["DB_PASSWORD"] %>
    port: <%= ENV["DB_PORT"] || "5432" %>
    username: <%= ENV["DB_USER"] %>
``
```

</blockquote></details>

Also works.

**Review by vtamara — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496)* status: 5 of 13 files reviewed, 11 unresolved discussions (waiting on @gscarv13, @Judahmeek, and @justin808)

___
*[Gemfile, line 54 at r1](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/496#-MzEOuCB4V4fSIwa8d9M:-MzLlVN01wsYwQE59rXm:b2mbz5f) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/b7e3156c60fa104624ddc06b823036316337a221/Gemfile#L54)):*
<details><summary><i>Previously, vtamara (Vladimir Támara Patiño) wrote…</i></summary><blockquote>

Removed.  Users in other OS's or for example in production can do: `.env && bundle exec foreman start -i Procfile.dev`
</blockquote></details>

Or better `bundle exec foreman start -i Procfile.devenv`

**Comment by justin808** [comment]
@ahangarha @Judahmeek anything useful here to extract or just close this one?

**Comment by Judahmeek** [comment]
Looks like there's some npm package & engine versions that we should relax.

Other than that, I believe we've already addressed everything relevant.

**Pull request closed without merging**
