### PR TITLE
Combine common items and remove duplication.

### PR DESCRIPTION
**Pull request by jDeppen**
PR references https://github.com/shakacode/react-webpack-rails-tutorial/commit/376ebe77af7f098e1aa1fd1aef2908ff1c599f90#commitcomment-17246669

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/281)

### CODE REVIEW

**Comment by justin808** [comment]
see comments, and let's squash to one commit

Thanks @jdeppen! 

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/webpack.client.base.config.js, line 22 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281#-KH3yF8WYlRuD2IVWo7-:-KH3yF8WYlRuD2IVWo70:-1570185412) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/f624eb69100d6c08358996fc261d090831ea3a06/client/webpack.client.base.config.js#L22)):*
this should not go here, as it's used here:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fwebpack.client.express.config.js#L6

and that setup does not use jquery-ujs

---

*[client/webpack.client.rails.build.config.js, line 20 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281#-KH3zYkmzVg1TtrLApm_:-KH3zYkmzVg1TtrLApma:1567236370) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8719099b51e45f83b7a2b60b6d2bb404a154d727/client/webpack.client.rails.build.config.js#L20)):*
OK, good

---

*[client/webpack.client.rails.build.config.js, line 21 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281#-KH3zZus09_JfGrLoF0R:-KH3zZus09_JfGrLoF0S:677787146) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8719099b51e45f83b7a2b60b6d2bb404a154d727/client/webpack.client.rails.build.config.js#L21)):*
keep

---

*[client/webpack.client.rails.hot.config.js, line 20 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281#-KH3zXf3Uy41McTBTsoZ:-KH3zXf3Uy41McTBTso_:677787146) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/8719099b51e45f83b7a2b60b6d2bb404a154d727/client/webpack.client.rails.hot.config.js#L20)):*
keep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281#-:-KH3za7t7BMFTb91pCCG:2020761689)*

**Comment by justin808** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/281)*

**Comment by jDeppen** [comment]
Sorry, I have a bunch of stuff on my plate and can't dedicate time to this. Maybe just toss it in with another PR?

**Comment by justin808** [comment]
@jDeppen I can take care of this

**Comment by justin808** [comment]
These were done a long time ago.

**Pull request closed without merging**
