### PR TITLE
Js update

### PR DESCRIPTION
**Pull request by faizan0009**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/450)

### CODE REVIEW

**Comment by justin808** [comment]
@faizan0009 CI needs to pass.

**Comment by faizan0009** [comment]
@justin808 
`"hot-assets": "NODE_ENV=development babel-node server-rails-hot.js",`

no this is useless now

**Comment by justin808** [comment]
If

> no this is useless now

then remove the old code

and references to it, etc.

**Comment by justin808** [comment]
@faizan0009 your upgrade from Webpack 3 to 4 is probably not right:

```
$ rm -rf ../public/webpack/test && NODE_ENV=test yarn run build:client && NODE_ENV=test yarn run build:server
$ webpack --config webpack.client.rails.build.config.js
Webpack dev build for Rails
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stderr:
(node:24498) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:24498) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846
		throw new Error(
		^
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846:9)
    at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1231:27)
    at hooks.make.callAsync.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compiler.js:546:17)
    at _done (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1082:12)
    at processModuleDependencies.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:998:9)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

**Comment by faizan0009** [comment]
> @faizan0009 your upgrade from Webpack 3 to 4 is probably not right:
> 
> ```
> $ rm -rf ../public/webpack/test && NODE_ENV=test yarn run build:client && NODE_ENV=test yarn run build:server
> $ webpack --config webpack.client.rails.build.config.js
> Webpack dev build for Rails
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> stderr:
> (node:24498) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> (node:24498) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
> /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846
> 		throw new Error(
> 		^
> Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
>     at Chunk.get (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846:9)
>     at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
>     at Array.forEach (<anonymous>)
>     at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
>     at AsyncSeriesHook.lazyCompileHook (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/Hook.js:154:20)
>     at Compilation.seal (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1231:27)
>     at hooks.make.callAsync.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compiler.js:546:17)
>     at _done (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
>     at _err1 (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
>     at _addModuleChain (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1082:12)
>     at processModuleDependencies.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:998:9)
>     at process.internalTickCallback (internal/process/next_tick.js:70:11)
> error Command failed with exit code 1.
> error Command failed with exit code 1.
> ```

@justin808 Strange, because it is working just fine locally

**Comment by justin808** [comment]
@faizan0009 any work solving the CI issues?

**Comment by faizan0009** [comment]
> @faizan0009 any work solving the CI issues?

@justin808 sorry no idea about this CI issue

**Comment by faizan0009** [comment]
@justin808 and upgrade from webpack 3 to 4 is correct, i have checked it multiple times.

**Comment by justin808** [comment]
@faizan0009 the build error was pretty clear:

```
Building Webpack assets...
================================================================================
React on Rails FATAL ERROR!
Error in building webpack assets!
cmd: cd "client" && yarn run build:test
exitstatus: 1
stdout:
yarn run v1.12.1
$ rm -rf ../public/webpack/test && NODE_ENV=test yarn run build:client && NODE_ENV=test yarn run build:server
$ webpack --config webpack.client.rails.build.config.js
Webpack dev build for Rails
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stderr:
(node:24498) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:24498) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846
		throw new Error(
		^
Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Chunk.js:846:9)
    at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1231:27)
    at hooks.make.callAsync.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compiler.js:546:17)
    at _done (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:1082:12)
    at processModuleDependencies.err (/home/travis/build/shakacode/react-webpack-rails-tutorial/client/node_modules/webpack/lib/Compilation.js:998:9)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

**Pull request closed without merging**
