### PR TITLE
Fix server-express startup

### PR DESCRIPTION
**Pull request by milushov**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/298)

### CODE REVIEW

**Comment by milushov** [comment]
Because we are using new es6 function syntax like `(req, res) => {}`

**Comment by justin808** [comment]
@milushov Thanks! I'll try to test this out today.

**Comment by justin808** [comment]
@milushov I just updated all dependencies. Please rebase your changes on top of that and confirm your fix works.

**Comment by justin808** [comment]
See #298

**Pull request closed without merging**
