### PR TITLE
Demo of Relay GraphQL implementation

### PR DESCRIPTION
**Pull request by ramusus**
TODO the next: 
- No server rendering. For server rendering we need to plug and use https://github.com/denvned/isomorphic-relay-router package. I tried without success..
- No optimistic update. Right now after new comment inserted, comments list reloading.

help wanted

This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/328)

### CODE REVIEW

**Comment by ramusus** [comment]
Created issue for Relay server rendering here https://github.com/denvned/isomorphic-relay-router/issues/54

**Comment by TigerWolf** [comment]
Any progress on this?

Is there anything I can help with?

**Comment by ramusus** [comment]
I do not maintain this PR anymore (switched to another project, where I don't need this feature), you are welcome to take it in your hands and / or reopen another PR based on my

**Comment by justin808** [comment]
@TigerWolf Give it a try and I'll review it!

**Comment by justin808** [comment]
Server rendering on top of GraphQL will become a part of [React on Rails Pro](https://github.com/shakacode/react_on_rails/wiki), as it supports a node rendering server which will be required for the server rendering.

That being said, it would be good to see this without the server rendering.

**Pull request closed without merging**
