### PR TITLE
Remove gulp, replaced by `npm run lint`

### PR DESCRIPTION
**Pull request by bronson**
Just an experiment, doesn't seem like gulp is actually needed...?

### CODE REVIEW

**Comment by alexfedoseev** [comment]
Haha, thanks @bronson! Currently I'm cleaning up everything in `/clients` dir on my local branch, it's one of the changes (:

**Comment by justin808** [comment]
@alexfedoseev If you approved, please merge this one. Looks OK to me, but maybe we'll get all your changes in at once.

**Comment by alexfedoseev** [comment]
@justin808 @bronson It looks good, there's some difference in npm commands structure on my local branch, I'll rebase it after merge to handle changes.

But there are [some issues](https://travis-ci.org/shakacode/react-webpack-rails-tutorial/builds/80692841) on travis with this PR. @dylangrafmyre @samnang Any Ideas?

**Comment by alexfedoseev** [comment]
Pushed my changes: https://github.com/shakacode/react-webpack-rails-tutorial/pull/96

**Comment by dylangrafmyre** [comment]
@alexfedoseev I will look into the travis build with this PR

**Comment by dylangrafmyre** [comment]
@alexfedoseev is your PR #96 superseding this PR? This will be closed when yours is merged, and I can ignore the travis-ci build error since your PR build is passing?

**Comment by alexfedoseev** [comment]
@dylangrafmyre Yes, I think this build error can be ignored.

**Comment by justin808** [comment]
@alexfedoseev @dylangrafmyre Are we removing this PR and replacing with #96? Or can we merge this to master and pull these changes into #96.

**Comment by dylangrafmyre** [comment]
@justin808 I believe we are going with @alexfedoseev branch #96, using his npm command structure.

**Pull request closed without merging**
