### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by justin808**
Note, had some issues with react-dom and history. Maybe these are not
needed.

We have a few deprecations to fix with React 0.14

### CODE REVIEW

**Comment by justin808** [comment]
test failures

```
  1) Add new comment Horizonal Form behaves like Comments Form submits form
     Got 0 failures and 2 other errors:
     Shared Example Group: "Comments Form" called from ./spec/features/comments_spec.rb:36

     1.1) Failure/Error: visit root_path
          Net::ReadTimeout:
            Net::ReadTimeout
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:133:in `get'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/navigation.rb:33:in `to'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:45:in `visit'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
          # ./spec/features/comments_spec.rb:28:in `block (2 levels) in <top (required)>'
          # ./spec/rails_helper.rb:44:in `block (3 levels) in <top (required)>'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
          # ./spec/rails_helper.rb:43:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: Unable to find matching line from backtrace
          NoMethodError:
            undefined method `render' for #<Capybara::Selenium::Driver:0x007ff7a43cf8e0>
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot.rb:104:in `block (2 levels) in <top (required)>'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/saver.rb:47:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/saver.rb:47:in `block in save_screenshot'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/saver.rb:74:in `clear_save_and_open_page_path'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/saver.rb:43:in `save_screenshot'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/saver.rb:26:in `save'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:57:in `block in after_failed_example'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara.rb:277:in `using_session'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
          # ./spec/rails_helper.rb:44:in `block (3 levels) in <top (required)>'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
          # ./spec/rails_helper.rb:43:in `block (2 levels) in <top (required)>'

Finished in 1 minute 30.14 seconds (files took 10.86 seconds to load)
4 examples, 1 failure

Failed examples:

rspec './spec/features/comments_spec.rb[1:1:1:1]' # Add new comment Horizonal Form behaves like Comments Form submits form
```

**Comment by alexfedoseev** [comment]
> react-dom

We need to change all render methods: `React.render` -> `ReactDOM.render`.

> history

Where do we use `history` module? It's used by `react-router`, but it's not used here yet.

**Comment by dylangrafmyre** [comment]
@justin808 This failure is local to your environment. I have a branch to fix the screenshot issue.

**Comment by dylangrafmyre** [comment]
This passed the CI builds and this issue must have had all our builds failing. I am going to merge and create another branch to fix the dependency issues from upgrading to React 0.14.0

**Pull request merged**
