### PR TITLE
Add eslint-shakacode-config

### LINKED ISSUE #228: need to add eslint-shakacode-config
https://github.com/shakacode/style-guide-javascript/tree/master/packages/eslint-config-shakacode

Any volunteers?

### PR DESCRIPTION
**Pull request by aaronvb**
Fixes #228

[Review on Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/233)

### CODE REVIEW

**Comment by justin808** [comment]
Thanks  @aaronvb. 

Are you sure we picked up any differences in the linter setups?

**Comment by aaronvb** [comment]
@justin808 Which setups? Airbnb and the shakacode config?

**Comment by justin808** [comment]
1. Ensuring that we're using any overrides from the shakacode config on npm.
2. We should possibly update the shakacode one to depend on the latest airbnb one.

**Comment by aaronvb** [comment]
@justin808 I tested and confirmed that is it adding the override configs from the eslint-shakacode-config, although right now there aren't any overrides. Also, the eslint-shakacode-config extends the airbnb config.

**Comment by justin808** [comment]
@aaronvb This file has the override: https://github.com/shakacode/style-guide-javascript/blob/master/packages/eslint-config-shakacode/rules/react.yml

Then again, that might not affect this project.

**Pull request merged**
