### PR TITLE
Added ActionCable

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/308)

### CODE REVIEW

**Comment by justin808** [comment]
@kubicek We should get this merged!
@jbhatab any interest?

**Comment by justin808** [comment]
@AlexKVal Any interest in taking a look at this one? Any opinions?

**Comment by justin808** [comment]
If we do this one, we need to make sure that we don't break: https://github.com/shakacode/react-native-tutorial.

**Comment by AlexKVal** [comment]
@justin808 I'll take a look at this after I end "Showing errors on pages" (I don't want PRs to be linked)

**Pull request closed without merging**
