### PR TITLE
isomorphic-fetch instead of axios

### PR DESCRIPTION
**Pull request by dzirtusss**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/323)

### CODE REVIEW

**Comment by dzirtusss** [comment]
Added `isomorphic-fetch` instead of `axios`. Draft.
Added temporary helper file `ror.js` -> future helpers that probably should go to ReactOnRails gem.

There is still a problem that `isomorphic-fetch` doesn't work in server rendering mode, so `config.prerender = false`

**Comment by dzirtusss** [comment]
Some thoughts/reasons:

- `checkStatus()` - needed because `fetch` presumes error checking and by default only raises error when some connection problems. W/o it `catch` will not work for ordinary errors. Also standard `response.ok` doesn't check for 304.

- remaining of `axios` structures
```
.then(res => res.json())
.then(res => ({ data: res }))
```
Jsut left this way. Can keep like this or need to restructure app further down to remove `data:`.

- `makeJsonPostHeader()` - kinda all-included POST. Need better naming.

- maybe in the end it good to have 3 helpers `getAuthenticityToken()`, `fetchJsonData()` and `makeJsonPostHeader()`

**Comment by justin808** [comment]
@dzirtusss We're not making any ajax requests when server rendering.

**Comment by justin808** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx, line 7 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBHts7f9oJxEzmSeL7:-KPBHts7f9oJxEzmSeL8:bcynhk7) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L7)):*
> ```JSX
> 
> import BaseComponent from 'libs/components/BaseComponent';
> import ror from 'libs/ror';
> ```

guessing this will go into ReactOnRails

---

*[client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx, line 33 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBHzyeDhZlxw7YDFBr:-KPBHzyeDhZlxw7YDFBs:bbt2s59) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L33)):*
> ```JSX
>     return (
>       fetch('comments.json')
>         .then(res => ror.checkStatus(res))
> ```

Maybe these 3 lines should go into some library call?

---

*[client/app/libs/ror.js, line 34 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBIDzAyWrzrzrpdFSO:-KPBIDzAyWrzrzrpdFSP:bhup6x5) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/client/app/libs/ror.js#L34)):*
> ```JavaScript
>       },
>       body: JSON.stringify(entity),
>       credentials: 'same-origin',
> ```

is this something new? the same-orgin part? Should ReactOnRails maybe make the whole header?

---

*[config/initializers/react_on_rails.rb, line 34 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBIWUB4_ecMfzoPeSE:-KPBIWUB4_ecMfzoPeSF:bwt5o6n) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/config/initializers/react_on_rails.rb#L34)):*
> ```Ruby
>   # Default is false. Can be overriden at the component level.
>   # Set to false for debugging issues before turning on to true.
>   config.prerender = false
> ```

this should not be necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323)*

**Comment by dzirtusss** [comment]
:confused:  Ok

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx, line 7 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBHts7f9oJxEzmSeL7:-KPCsK_36SVNWRsn_FvS:b-ujy3ef) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L7)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> guessing this will go into ReactOnRails
</details>
yes - what is in `ror.js` file can possibly go to gem

---

*[client/app/libs/ror.js, line 34 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBIDzAyWrzrzrpdFSO:-KPCsgPzAqvqpiGBvnQj:b85tsuo) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/client/app/libs/ror.js#L34)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> is this something new? the same-orgin part? Should ReactOnRails maybe make the whole header?
</details>
This is needed to pass session cookie to Rails inside request. It is fetch specific line.

For pure fetch compared vs axios it is needed much more configs like `same-origin`. `checkStatus` helper

---

*[config/initializers/react_on_rails.rb, line 34 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-KPBIWUB4_ecMfzoPeSE:-KPCtigOGveN-qfGWo3t:b32w1t) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/c0e2fbf1d41846f0816b2789c47c0f6348465e47/config/initializers/react_on_rails.rb#L34)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> this should not be necessary
</details>
Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/323#-:-KPCtlGw4YPEDq6CPk5Q:b-f31ha8)*

**Comment by dzirtusss** [comment]
@justin808

There are still 2 issues with isomorphic-fetch:

1) doesn't work in server-render mode
2) last PR #321 about error handling is dependent on axios `responce.error` and `responce.error.data` when rendering error message, which we don't have in fetch

What to do?

**Comment by justin808** [comment]
@dzirtusss:

1. We shouldn't be calling the fetch when server rendering.
2. Please check with @AlexKVal on the 2nd issue.

**Comment by justin808** [comment]
I'm open to reasons why or why this should not be merged (after rebasing on master).

**Pull request closed without merging**
