### PR TITLE
Upgrade react-webpack-rails-tutorial to Webpacker Lite

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/395)

### CODE REVIEW

**Comment by kevinhughes27** [comment]
I had to add `HOT_RELOADING=TRUE` to my Procfile in addition to these changes to ensure webpacker_lite is also expecting reloading.

https://github.com/shakacode/webpacker_lite/blob/master/lib/webpacker_lite/env.rb#L14
https://github.com/shakacode/webpacker_lite/blob/master/lib/webpacker_lite/configuration.rb#L24

**Comment by justin808** [comment]
@Judahmeek @kevinhughes27  is this something that should be added?

**Comment by kevinhughes27** [comment]
I was initially expecting `REACT_ON_RAILS_ENV=HOT` to set this up for me. I think ideally we wouldn't set 2 ENV vars in the Procfile but that's just my opinion.

**Comment by justin808** [comment]
@kevinhughes27, @judahmeek, @conturbo, we need to finish up the half completed work of moving to React on Rails v8:

1. Remove REACT_ON_RAILS_ENV, as that's no longer used for v8. See [search](https://github.com/shakacode/react-webpack-rails-tutorial/search?utf8=%E2%9C%93&q=REACT_ON_RAILS_ENV&type=)
2. Fix hot reloading in here: https://github.com/shakacode/react-webpack-rails-tutorial/issues/361

**Comment by kevinhughes27** [comment]
I'm happy to PR the `REACT_ON_RAILS_ENV` changes to the example repo. I started implementing the changes in #361 but given the state of my project I need to continue using the old hot reloader since I can't have a root component until I finish more refactoring. I'm not sure how many others would be in that state or how much the focus of react_on_rails is for old apps vs new apps.

**Pull request merged**
