### PR TITLE
Express server rendering

### PR DESCRIPTION
**Pull request by justin808**
Fixes to reenable express server rendering.

* Had to work around no shared store support
* https://github.com/shakacode/react_on_rails/issues/504

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/313)

### CODE REVIEW

**Comment by justin808** [comment]
@robwise Please review.

**Comment by robwise** [comment]
:lgtm:


this thing is becoming a giant confusing mess, so it's good that we're now trimming the fat (recommending against express server).

However, adding comments with code examples only to say that the example code wrote won't work is going in the wrong direction.

---

Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/index.pug, line 19 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FAdYTKUJQBDLxKNC:-KO4FAdYTKUJQBDLxKND:1940804258) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/index.pug#L19)):*
> ```Jade
>     //  ReactOnRails.reduxStore('routerCommentsStore', !{props});
>     // script.
>     //  ReactOnRails.render('RouterApp', !{}, 'app');
> ```

keep something about how we are doing a special start up because we're client-side only, but including the stuff above actually makes this substantially more confusing

---

*[client/server-express.js, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FTzzoGD6uTSASm-6:-KO4FTzzoGD6uTSASm-7:1823310028) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/server-express.js#L34)):*
> ```JavaScript
>   sleep.sleep(1);
>   res.setHeader('Content-Type', 'application/json');
>   res.send(JSON.stringify({ comments }));
> ```

j/c why this change?

---

*[client/webpack.client.express.config.js, line 15 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FZIRIBwEWkNELLJN:-KO4FZIRIBwEWkNELLJO:442930873) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/webpack.client.express.config.js#L15)):*
> ```JavaScript
>   // Shouldn't be necessary:
>   // https://github.com/shakacode/react_on_rails/issues/504
>   './app/bundles/comments/startup/ClientRouterAppExpress',
> ```

delete this. let's think of ways to make this repo more concise instead of cramming more stuff in

---

*[client/app/bundles/comments/startup/ClientRouterAppExpress.jsx, line 2 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4GJqn0wPftjBsnr81:-KO4GJqoZUT6eAB4Pmgu:-1342328708) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/app/bundles/comments/startup/ClientRouterAppExpress.jsx#L2)):*
> ```JSX
> // Compare to ../ServerRouterApp.jsx
> // This
> ```

`// This `?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-:-KO4GWy7ojGXuBeBY3F4:235339861)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/index.pug, line 19 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FAdYTKUJQBDLxKNC:-KO4MiaT7aIH3IQLVPII:-1922901900) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/index.pug#L19)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> keep something about how we are doing a special start up because we're client-side only, but including the stuff above actually makes this substantially more confusing
</details>
I'm just saying this is how it could be done...

---

*[client/server-express.js, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FTzzoGD6uTSASm-6:-KO4MdAywiu-FJJD11_o:987766797) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/server-express.js#L34)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> j/c why this change?
</details>
Old code was wrong.

---

*[client/webpack.client.express.config.js, line 15 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FZIRIBwEWkNELLJN:-KO4MpO4NeFTzS_Ebs9r:-1971885453) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/webpack.client.express.config.js#L15)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> delete this. let's think of ways to make this repo more concise instead of cramming more stuff in
</details>
delete this? Then rest of this PR won't work.

---

*[client/app/bundles/comments/startup/ClientRouterAppExpress.jsx, line 2 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4GJqn0wPftjBsnr81:-KO4MtM8SH4qITYUBsyY:1598331703) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/app/bundles/comments/startup/ClientRouterAppExpress.jsx#L2)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> `// This `?
</details>
yep -- delete that line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313)*

**Comment by justin808** [comment]
Maybe we merge this in, and then do another PR that removes the express-server rendering?

---

Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-:-KO4NKnfq6vwKiPKMIo1:152208834)*

**Comment by robwise** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/server-express.js, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FTzzoGD6uTSASm-6:-KO4RUg3sgXXlXtDxkg7:-1410330560) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/server-express.js#L34)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> Old code was wrong.
</details>
how revealing

---

*[client/webpack.client.express.config.js, line 15 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FZIRIBwEWkNELLJN:-KO4QsNYiS4hiuiREYJ-:2141414763) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/webpack.client.express.config.js#L15)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary>
> delete this? Then rest of this PR won't work.
</details>
your comment says it shouldn't be necessary and links to an issue regarding how something isn't implemented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313)*

**Comment by justin808** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/server-express.js, line 34 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FTzzoGD6uTSASm-6:-KO6fiw4vI1n2Wl3gJzc:709394780) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/server-express.js#L34)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> how revealing
</details>
do I sense sarcasm?

---

*[client/webpack.client.express.config.js, line 15 \[r2\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313#-KO4FZIRIBwEWkNELLJN:-KO6folmLwWk6nWS9Sdc:-799158714) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/94c72bd41ff16a85e943b7de009a85ec7bdb8f71/client/webpack.client.express.config.js#L15)):*
<details><summary><i>Previously, robwise (Rob Wise) wrote…</i></summary>
> your comment says it shouldn't be necessary and links to an issue regarding how something isn't implemented
</details>
OK -- delete the comment, not file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/313)*

**Pull request merged**
