### PR TITLE
updating deps, also putting capybara screenshots somewhere sane

### PR DESCRIPTION
**Pull request by brucek**
Hopefully these small updates are useful, but at least the capybara fix should help.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/275)

### CODE REVIEW

**Comment by justin808** [comment]
@brucek These look great. Can you take a look at why CI (travis) is failing?

**Comment by brucek** [comment]
I should have linted :-/  Hopefully this one will pass.

**Comment by justin808** [comment]
:lgtm:

Thanks!

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/275#-:-KFLxP3weFChp7TBnB-H:563354983)*

**Comment by justin808** [comment]
@brucek can you please rebase on top of origin/master and I'll merge.

**Pull request merged**
