### PR TITLE
Fix references between procfiles

### PR DESCRIPTION
**Pull request by roxolan**
It seems like Procfile.rails transmutated into Procfile.hot, didn't it? And it also is responsible for a part of what is declared in Procfile.dev.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/285)

### CODE REVIEW

**Comment by justin808** [comment]
Why is the README.md in the change list?

One comment and let's squash the commits and I'll merge.

Thanks @roxolan 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Procfile.hot, line 1 \[r1\]](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/285#-KH3ypXTtV8QFuf-KDY7:-KH3ypXTtV8QFuf-KDY8:-1388045) ([raw file](https://github.com/shakacode/react-webpack-rails-tutorial/blob/a9009522aeb4fa62e0645fd6ab0b659f55f15e0d/Procfile.hot#L1)):*
Let's add this to the end of the sentence:

using a webpack development server to load JavaScript and CSS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/react-webpack-rails-tutorial/285#-:-KH3z6CQoausP1tACrzj:1976534310)*

**Comment by roxolan** [comment]
Thank you. README.md contains reference to the old Procfile.rails, which I thought was worth fixing (line 98). Emacs cleaned up some whitespace automatically, I hope it's ok, too.

**Comment by justin808** [comment]
Please rebase to one commit on top of master. Thanks!

**Comment by roxolan** [comment]
I am sorry, I'm not fully sure if I did everything right: I just updated the branch by merging. Would you like me to resubmit the whole thing in another pull request as just one commit?

**Pull request closed without merging**
