### PR TITLE
Turbolinks 5 and React on Rails v3.0.0-RC.2

### PR DESCRIPTION
**Pull request by justin808**
[Review on Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/229)

### CODE REVIEW

**Comment by aaronvb** [comment]
The event in `rails_startup.js` will need to be updated for the nav class to be active or not active.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/app/assets/javascripts/rails_startup.js#L1

```javascript
$(document).on('ready page:load', function () {
```

to Turbolinks 5:

```javascript
$(document).on('ready turbolinks:load', function () {
```

**Comment by justin808** [comment]
thanks @aaronvb I had that as well!

**Comment by justin808** [comment]
@aaronvb @alexfedoseev :+1: ???

**Comment by aaronvb** [comment]
@justin808 LGTM :+1:

**Comment by alexfedoseev** [comment]
My :+1:

**Pull request merged**
