### PR TITLE
Demonstrate react-router

### PR DESCRIPTION
**Pull request by josiasds**
This is a basic example I've done with @alexfedoseev for demonstrate react-router (#72).

### CODE REVIEW

**Comment by justin808** [comment]
@josiasds Is this ready to go? Is there any test that we should add to this?

**Comment by josiasds** [comment]
@justin808 It's ready. Not sure if there is something to test here.

**Comment by justin808** [comment]
@rstormsf @josiasds can you please discuss @rstormsf's last comment. I'm not sure what it means. Also, please rebase the changes on top of master. I just added the react_on_rails gem.

**Comment by alexfedoseev** [comment]
@rstormsf is right, `beta4` breaks the things.

**Comment by alexfedoseev** [comment]
@josiasds Ping me when you'll have time for this.

**Comment by josiasds** [comment]
Ok, react-router version is fixed.

This PR adds the Layout component, a wrapper containing a header with two links:
- `/` redirects to the existing component `CommentScreen`;
- `/about` redirects to a new component named `About`.

The routes are handled by `routes.jsx`.

screen shot 2015-09-08 at 09 00 30

It seems to be working fine with the react_on_rails gem.

**Comment by terry-s** [comment]
@josiasds, what about server-rendering with react-router?

**Comment by alexfedoseev** [comment]
@terry-s We need 1-2 weeks from the moment when `react-router@1.0.0` will be released.

**Comment by justin808** [comment]
Wow, wow, wow! https://github.com/rackt/react-router/issues/1777#issuecomment-138565787

Going to be fixed in a few weeks!

**Comment by justin808** [comment]
@josiasds @alexfedoseev We should rebase to master and pick this one up in the not to distant future. Can we do server rendering with react-router yet?

**Comment by alexfedoseev** [comment]
@justin808 Not yet, I need to update the status of the react-router's server API. Yesterday I was updating node setup to `1.0.0-rc3` and it's changed again.

**Comment by alexfedoseev** [comment]
Let's continue in #128.

**Pull request closed without merging**
