### PR TITLE
Include `.git` directory in the Docker image

### PR DESCRIPTION
**Pull request by ahangarha**
We need to have the `.git` directory in the deployed project to get and show the commit hash of the deployed project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/569)

### CODE REVIEW

**Comment by justin808** [comment]
This is incorrect AFAIK. @borela how do you get the commit better in docker builds?

**Review by justin808 — COMMENTED** [review]
see prior comment

**Comment by borela** [comment]
You can use [ARGs](https://medium.com/@johnidouglasmarangon/accessing-docker-tag-as-an-environment-variable-inside-a-docker-container-project-6d944cab4ff7) and pass the commit during the build command.

**Review by borela — CHANGES_REQUESTED** [review]
You can use [ARGs](https://medium.com/@johnidouglasmarangon/accessing-docker-tag-as-an-environment-variable-inside-a-docker-container-project-6d944cab4ff7) and pass the commit to the build command.

**Comment by ahangarha** [comment]
> You can use [ARGs](https://medium.com/@johnidouglasmarangon/accessing-docker-tag-as-an-environment-variable-inside-a-docker-container-project-6d944cab4ff7) and pass the commit to the build command.

But we use `cpl` to build images to deploy on ControlPlane.
We need another mechanism to do this.

**Comment by borela** [comment]
@ahangarha we need to update the tool to be able to pass args to the docker image too, people might need it for other purposes.

**Comment by ahangarha** [comment]
@borela Got it.
So this is a good example to test the feature.
Should I open a new issue on [CPL project](https://github.com/shakacode/heroku-to-control-plane/)?

**Comment by justin808** [comment]
See https://github.com/shakacode/heroku-to-control-plane/issues/117

**Comment by justin808** [comment]
See #117

**Comment by justin808** [comment]
Why? 
[Ask ChatGPT](https://chat.openai.com/share/f868845e-7b24-44da-b9b5-efc1a839ada6)

why should the .git directory be included in a .dockerignore
ChatGPT
Including the .git directory in a .dockerignore file is a recommended practice for several reasons:

Reduce Image Size: .git directories often contain a lot of metadata and historical data that are not necessary for running the application. Excluding this directory can significantly reduce the size of the Docker image.

Security: The .git directory may contain sensitive information, such as commit history, configuration details, or even credentials in some cases. Excluding it from the Docker image helps to prevent unintended exposure of this information.

Build Efficiency: Docker builds can be faster when the context sent to the Docker daemon is smaller. The .git directory can be quite large, especially for long-standing projects, so excluding it can speed up the build process.

Clean Environment: Docker images are intended to be minimal and specific to the application's runtime requirements. Including only what is necessary for the application to run ensures a clean, minimal environment, which is a best practice for Docker usage.

Avoid Unnecessary Rebuilds: Docker uses the context sent to the daemon to determine if an image needs to be rebuilt. Changes in the .git directory that are irrelevant to the application's functionality could trigger unnecessary rebuilds, thus excluding it can help in avoiding this.

Compliance and Best Practices: For compliance with various security and operational best practices, it's essential to keep Docker images lean and free from unnecessary files. This aids in maintaining a standardized and secure deployment process.

In summary, excluding the .git directory from Docker builds results in smaller, more secure, and efficient images, aligning with best practices for Docker usage.

**Pull request closed without merging**
