### PR TITLE
Updated Ruby Version and Gem File

### PR DESCRIPTION
**Pull request by singhvaibhavram**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/react-webpack-rails-tutorial/447)

### CODE REVIEW

**Comment by justin808** [comment]
@singhvaibhavram CI is not passing. Can you take a look?

**Comment by singhvaibhavram** [comment]
Yes the reason is this.  

foreman start -f Procfile.hot00:52:00 rails.1               | started with pid 24959
00:52:00 hot-assets.1          | started with pid 24960
00:52:00 rails-server-assets.1 | started with pid 24962
00h00m00s 0/0: : 00:52:00 rails-server-assets.1 | ERROR: [Errno 2] No such file or directory: 'run'
00:52:01 rails-server-assets.1 | exited with code 1
00:52:01 system                | sending SIGTERM to all processes
00:52:01 rails.1               | terminated by SIGTERM
00:52:01 hot-assets.1          | terminated by SIGTERM

**Comment by singhvaibhavram** [comment]
trying to solve this

**Comment by singhvaibhavram** [comment]
@justin808

**Comment by justin808** [comment]
@singhvaibhavram CI is failing. Did you check?

**Pull request closed without merging**
