### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### justin808/react-webpack-rails-tutorial now has a Chat Room on Gitter

@justin808 has just created a chat room. You can visit it here: [https://gitter.im/justin808/react-webpack-rails-tutorial](https://gitter.im/justin808/react-webpack-rails-tutorial?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/justin808/react-webpack-rails-tutorial?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by justin808** [comment]
@dylangrafmyre @mbreining @alexfedoseev @geoffevason Any opinions on this one?

**Comment by geoffevason** [comment]
Another place to chat? You're going to run out of browser tabs...  I suppose if a slack like experience is good to discuss this specific repo is what you want, then it's okay - but keeping conversations on github is probably better imho

**Comment by dylangrafmyre** [comment]
@justin808 Since we have our gitter link in the ReadMe, we should just add this badge and remove the link. I think it will be easier for people to spot and use. I can fix the conflicts and merge?

**Comment by justin808** [comment]
Sound fine. I log in every once in a while to gitter.

**Comment by samnang** [comment]
If we don't have many use gitter, why don't we just stick with slack and we already have many members are online in slack already.

https://github.com/rauchg/slackin

**Comment by dylangrafmyre** [comment]
I agree with @samnang, but if we keep a link to gitter on the ReadMe we are better off with the badge.

**Comment by justin808** [comment]
I'm indifferent on this one. We invite people to slack. Anybody can chat on gitter.

**Pull request closed without merging**
