### PR TITLE
Upadate README

### PR DESCRIPTION
**Pull request by szyablitsky**
CI configuration

### CODE REVIEW

**Comment by szyablitsky** [comment]
If we move away from Travis CI, then we lose info on proper CI configuration which now is only contained in `.travis.yml`

**Comment by alexfedoseev** [comment]
After merge of #96 it should be:

```
npm install
cd client && npm run build
```

**Comment by szyablitsky** [comment]
@alexfedoseev Fixed. Thanks!

**Comment by alexfedoseev** [comment]
Thanks! :+1: I'll merge it after #96

**Comment by alexfedoseev** [comment]
@szyablitsky #96 is merged.
Here is the final travis config: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/.travis.yml
Please make one more fix and I'll merge it to master. Thanks!

**Comment by szyablitsky** [comment]
@alexfedoseev Done!

**Comment by alexfedoseev** [comment]
@szyablitsky Merged :+1:

**Pull request merged**
